INCLUDE=-I ./ -I ../utils/ -I ../common/ -I../utils/bstr
intertask_interface.o: intertask_interface.c backtrace.c memory_pools.c  signals.c timer.c 
	gcc -c intertask_interface.c backtrace.c memory_pools.c  signals.c timer.c $(INCLUDE) -w
backtrace.o: backtrace.c
	gcc -c backtrace.c
memory_pools.o: memory_pools.c
	gcc -c memory_pools.c $(INCLUDE)
dynamic_memory_check.o : ../utils/dynamic_memory_check.c
	gcc -c ../utils/dynamic_memory_check.c $(INCLUDE)
signals.o: signals.c
	gcc -c signals.c $(INCLUDE)
timer.o: timer.c
	gcc -c timer.c $(INCLUDE)
clean:
	rm timer.o signals.o memory_pools.o backtrace.o intertask_interface.o ../utils/dynamic_memory_check.o
